### ISSUE TITLE
[IANA Registry] attested_security_context as JWT parameter

### ISSUE THREAD

**Issue by peppelinux** [oauth-wg/draft-ietf-oauth-attestation-based-client-auth#29]
The brand new parameter called `attested_security_context`, as defined [here](https://github.com/vcstuff/draft-looker-oauth-attestation-based-client-auth/pull/26/files#diff-55e05bec82593426ed363ab5c93ddf1e82b0f64cdf164f98e85fe1236b8783edR325), requires a IANA section for the registration of this parameter name

**Comment by tplooker** [comment]
Registration is no longer required as this section was shifted to a non-normative example. We are still discussing as editors whether registration of some form of claim for this purpose is valuable for the draft.

**Comment by paulbastian** [comment]
key attestations and associated parameters will be handled separately in [OpenID4VCI](https://github.com/openid/OpenID4VCI/pull/389)
