### ISSUE TITLE
typ values for Client Attestation JWT and Client Attestation PoP JWT

### ISSUE THREAD

**Issue by TakahikoKawasaki** [oauth-wg/draft-ietf-oauth-attestation-based-client-auth#30]
The current draft does not require the Client Attestation JWT and Client Attestation PoP JWT to have the `typ` JWS header parameter. Do you have any plans to define specific `typ` values for these JWTs?

**Comment by paulbastian** [comment]
Agreed. Need to properly define header section

**Comment by tplooker** [comment]
May also require IANA considerations for registration.

**Comment by paulbastian** [comment]
Proposing `jwt-client-attestation` , `jwt-client-attestation-pop`

**Comment by bc-pi** [comment]
JWS/JWT typ is a media type and based on https://datatracker.ietf.org/doc/html/rfc8725#name-use-explicit-typing I'd propose something like `oauth-client-attestation+jwt` and `oauth-client-attestation-pop+jwt`

And FWIW you can kinda follow how DPoP registered and used the `application/dpop+jwt` media type to allow for explicit typing there https://www.rfc-editor.org/rfc/rfc9449.html or `application/at+jwt` from https://datatracker.ietf.org/doc/html/rfc9068
